// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using directory;

namespace directory.Migrations
{
    [DbContext(typeof(Store.StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("directory.Store+Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryName");

                    b.HasKey("categoryID");

                    b.ToTable("category");
                });

            modelBuilder.Entity("directory.Store+Customer", b =>
                {
                    b.Property<int>("custID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("emailAddress");

                    b.Property<string>("phoneNumber");

                    b.Property<int>("postalCode");

                    b.Property<string>("shipAddress");

                    b.Property<string>("shipCity");

                    b.Property<string>("shipCountry");

                    b.Property<string>("shipName");

                    b.Property<string>("shipRegion");

                    b.HasKey("custID");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("directory.Store+Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("custID");

                    b.Property<string>("orderDate");

                    b.Property<int>("postalCode");

                    b.Property<string>("shipAddress");

                    b.Property<string>("shipCity");

                    b.Property<string>("shipCountry");

                    b.Property<string>("shipDate");

                    b.Property<string>("shipName");

                    b.Property<string>("shipRegion");

                    b.HasKey("OrderID");

                    b.ToTable("order");
                });

            modelBuilder.Entity("directory.Store+OrderDetails", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("productID");

                    b.Property<int>("quantity");

                    b.Property<double>("unitPrice");

                    b.HasKey("orderID");

                    b.ToTable("orderDetail");
                });

            modelBuilder.Entity("directory.Store+Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("availability");

                    b.Property<int>("categoryID");

                    b.Property<int>("supplierID");

                    b.Property<double>("unitPrice");

                    b.HasKey("productID");

                    b.ToTable("product");
                });

            modelBuilder.Entity("directory.Store+Supplier", b =>
                {
                    b.Property<int>("supplierID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<string>("city");

                    b.Property<string>("companyName");

                    b.Property<string>("contactName");

                    b.Property<string>("country");

                    b.Property<string>("fax");

                    b.Property<string>("phoneNumber");

                    b.Property<int>("postalCode");

                    b.Property<string>("region");

                    b.HasKey("supplierID");

                    b.ToTable("supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
